LKVoxR = LKVoxR or {}

LKVOXR_RENDER_RES_X = 128
LKVOXR_RENDER_RES_Y = 128
LKVOXR_TRACE_STEPS = 32
LKVOXR_DO_SHADOWS = false

LKVOXR_DYNFPS_FPS_TARGET = 30
LKVOXR_DYNFPS_RES_LOWER_STEP = 4
LKVOXR_DYNFPS_RES_MIN_X = 64
LKVOXR_DYNFPS_RES_MIN_Y = 64
LKVOXR_DYNFPS_RES_MAX_X = 512
LKVOXR_DYNFPS_RES_MAX_Y = 512


LKVOXR_DYNFPS_TRACESTEPS_MIN = 8
LKVOXR_DYNFPS_TRACESTEPS_LOWER_STEP = 1

LKVOXR_FOV = 90

LKVOXR_CHUNK_X = 16
LKVOXR_CHUNK_Y = 128
LKVOXR_CHUNK_Z = 16 -- 16 x 16 x 16

LKVOXR_CX_P = LKVOXR_CHUNK_X + 1
LKVOXR_CY_P = LKVOXR_CHUNK_Y + 1
LKVOXR_CZ_P = LKVOXR_CHUNK_Z + 1


LKVOXR_MAX_Y = 129


